[package]
name = "rodisnyaa"
version = "0.1.0"
edition = "2024"
description = "nya"
license = "MIT OR Apache-2.0"

[lib]
name = "rodisnyaa"
path = "src/lib.rs"

[dependencies]
dasp_sample = "0.11"
rodio = { version = "0.22", features = [
    "mp3",
    "playback",
    "vorbis",
    "wasm-bindgen",
    "wav",
] }
log = "0.4"
parking_lot_core = { version = "0.9", optional = true }
symphonia = "0.6"
thiserror = "2"
web-time = "1"

[features]
default = ["nightly"]
nightly = ["cpal/audioworklet", "parking_lot_core/nightly"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
cpal = { version = "0.17", features = ["wasm-bindgen"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
getrandom = { version = "0.4", features = ["wasm_js"] }
web-sys = { version = "0.3", features = [
    "Window",
    "AudioContext",
    "AudioContextState",
    "Response",
    "console",
] }

[dev-dependencies]

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"
