[tools]
"github:oxc-project/oxc" = { version = "latest", matching = "oxfmt" }
lefthook = "latest"
rust = { version = "nightly-2026-03-12", components = [
    "clippy",
    "rustfmt",
    "rust-src",
] }


[hooks]
postinstall = ["lefthook install"]
