[tools]
"github:oxc-project/oxc" = { version = "latest", matching = "oxfmt" }
lefthook = "latest"
rust = { version = "nightly-2026-03-12", components = [
    "clippy",
    "rustfmt",
    "rust-src",
] }


[hooks]
postinstall = ["lefthook install"]

[tasks.check]
run = "mise lint && mise format:cargo --check && mise format:oxfmt --check"

[tasks.format]
depends = ["format:cargo", "format:oxfmt"]

[tasks."format:cargo"]
run = "cargo fmt --all"

[tasks."format:oxfmt"]
run = "oxfmt"

[tasks.lint]
run = "cargo clippy --all-targets --all-features --workspace -- -D warnings"

[tasks.test]
depends = ["test:native", "test:wasm"]

[tasks."test:native"]
run = "cargo test --workspace -- -Zunstable-options --format=terse"

[tasks."test:wasm"]
run = "wasm-pack test --headless --chrome . "
